### ISSUE TITLE
endpoint example please

### ISSUE THREAD

**Issue by sebdalgarno** [greatislander/littoral-zone#70]
hi @greatislander. Thanks for your work on this!
sorry this isn't exactly an issue, but I'm interested in using the API and am struggling to get it working. 
Can you provide an example of a working url endpoint?
e.g. `https://api.littoral.zone/levels/54.0115,-132.1472/` not working...

**Comment by greatislander** [comment]
Hi @sebdalgarno, thanks for your interest. This is a side project in very early stages and doesn't work yet. I haven't touched it in the last couple of years and don't anticipate having any time to work on it in the near future.

**Comment by sebdalgarno** [comment]
oh I see no worries!
